### ISSUE TITLE
RPC port 8332 should be localhost only

### ISSUE THREAD

**Issue by harding** [jamesob/docker-btc#11]
I know very little about docker, so please forgive me if I'm confused.  The README suggests starting with the following parameter:

    -p 8332:8332 \

[This Docker manual](https://docs.docker.com/network/links/#connect-using-network-port-mapping) says that will bind bitcoind's RPC port to the host systems port 8332 listening on all interfaces.  Since RPC is unencrypted by default (even the authentication), it would probably be better to bind to just localhost.  The above page suggests that could be done with:

    -p 127.0.0.1:8332:8332

Note, this issue with Docker was first described here: https://twitter.com/LaurentMT/status/1067796761161490432

**Comment by jamesob** [comment]
Nice catch, @harding! Thanks. Fixed in https://github.com/jamesob/docker-bitcoind/commit/b3c7a396d7cbbdd6973d1b51bdb0562bc60ec37e.
