### ISSUE TITLE
World-readable bitcoin.conf

### ISSUE THREAD

**Issue by alecov** [jamesob/docker-btc#17]
As per the title. This leaks RPC credentials.

Add a `chmod 600 "${BITCOIN_CONF}"` right after this line:
https://github.com/jamesob/docker-bitcoind/blob/1e046385d7d8bd551c90cbfc19c8500b3b0f33d0/bin/docker_entrypoint.sh#L60

**Comment by jamesob** [comment]
Yep thanks, willfix. This repo needs numerous security improvements including verifying binary hashes.

**Comment by jamesob** [comment]
Fixed in https://github.com/jamesob/docker-bitcoind/commit/f85884bbf46e57e275f64579a2e545f671b114d7. Thanks for the report!
