### ISSUE TITLE
Missing bin/append-to-hosts.sh

### ISSUE THREAD

**Issue by paulp** [jamesob/docker-btc#19]
```
# Workaround to address https://github.com/jamesob/docker-bitcoind/pull/16 while
# still not running as root user.
COPY ./bin/append-to-hosts.sh /usr/bin/append-to-hosts
RUN chmod +x /usr/bin/append-to-hosts
```
This file is absent from the repository, causing docker build to give up at that point.

**Comment by jamesob** [comment]
Oof, my mistake. Fixed in https://github.com/jamesob/docker-bitcoind/commit/b2fb587cd760334581a2d7c23be6ae92174e3819 - thanks for the report!
