### ISSUE TITLE
how to start bitcoind with arguments

### ISSUE THREAD

**Issue by gggin** [jamesob/docker-btc#9]
I stop the container and then bitcoin-core let me to use -reindex to build UTXOs. But I can't.
I'm a newbie to Docker.

Thank you very much.

**Comment by jamesob** [comment]
You should be able to run whatever command you'd like based on the entrypoint (https://github.com/jamesob/docker-bitcoind/blob/master/entrypoint.sh#L88-L91). For example, if you'd like to run a reindex, you could do:
```sh
docker run \
   -v ${HOME}/.bitcoin:/bitcoin/data \
   -p 127.0.0.1:8332:8332 \
   -p 8333:8333 \
   jamesob/bitcoind:0.20.1 bitcoind -datadir=/bitcoin/data -conf=/bitcoin/bitcoin.conf -reindex
```
